services:
  db:
    image: postgres:16
    container_name: anglo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AngloElectric123  
      POSTGRES_DB: anglo_electric_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: anglo_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@angloelectric.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data: